server:
    port: 8081

spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://localhost:5432/user_service_db
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: auth-service
