spring:
    application:
        name: auth-service

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_batch_fetch_size: 100

    data:
        redis:
            host: redis
            port: 6379
            password: ${REDIS_PASSWORD}

    cloud:
        openfeign:
            client:
                config:
                    default:
                        connect-timeout: 5000
                        read-timeout: 5000

management:
    endpoints:
        web:
            exposure:
                include: health, prometheus

logging:
    level:
        com.weave: DEBUG

springdoc:
    override-with-generic-response: false